objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <inlineHelpText>Dealer code to receive credit for opportunity</inlineHelpText>
        <label>Assigned Dealer</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credited Dealer for Opportunity</inlineHelpText>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Assigned Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Dealer_Code__c</fullName>
        <formula>Territory2.Dealer_Code__c</formula>
        <label>Territory Dealer Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/Vgtna_batchAssignTerrToOppty.cls
/**
* @author         salesforce services       
* @date           11/28/2018
* @description    Batch class to assign terrirory2id to opportunity running in a sys admin mode.
*           
*
*
*/
global class Vgtna_batchAssignTerrToOppty implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
            // collect the batches of records or objects to be passed to execute
             
           // String query = 'SELECT Id,Name,AccountId,Territory2Id,Territory_Dealer_Code__c,Partner_Account__c,Partner_Account__r.Dealer_Code__c,LastModifiedDate FROM Opportunity Where Partner_Account__r.Dealer_Code__c!= null or Territory_Dealer_Code__c != null';
           String query = 'SELECT Id,Name,AccountId,Territory2Id,Territory_Dealer_Code__c,Partner_Account__c,Partner_Account__r.Dealer_Code__c,LastModifiedDate FROM Opportunity Where SystemModStamp >= LAST_N_DAYS:1 AND (Partner_Account__r.Dealer_Code__c!= null OR Territory_Dealer_Code__c != null)';
        system.debug('query-->'+query);
        	return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Opportunity> oppList)
    {
        
        // process each batch of records
 		Map<String, Opportunity> dealerCode2OpptyMap = new Map<String, Opportunity>();
        Set<String> dealerCodes = new Set<String>();
        List<Opportunity> oppsToBeUpdated = new List<Opportunity>();
        
        for(Opportunity oppty: oppList)
        {
            if(oppty.Partner_Account__r.Dealer_Code__c == null && oppty.Territory_Dealer_Code__c != null)
            {
                oppty.Territory2Id = null;
                oppsToBeUpdated.add(oppty);
            }
            else
            {
                dealerCodes.add(oppty.Partner_Account__r.Dealer_Code__c);
            	dealerCode2OpptyMap.put(oppty.Partner_Account__r.Dealer_Code__c,oppty); 
            }
            
        }
        if(!dealerCodes.isEmpty())
        {
            Map<String,Territory2> matchingTerrIds = vgtna_TerritoryModel.findTerritoryID(dealerCodes);
            System.debug('matchingTerrIds--->'+ matchingTerrIds);
            
                     if(!matchingTerrIds.isEmpty())
                     {
                         for(Opportunity o: oppList)
                         {
                             if(matchingTerrIds.get(o.Partner_Account__r.Dealer_Code__c) != null)
                             {
                                 o.Territory2Id = matchingTerrIds.get(o.Partner_Account__r.Dealer_Code__c).id;
                                 oppsToBeUpdated.add(o);
                             }
                         }
                         
                         
                     }
             }
        
        	if(!oppsToBeUpdated.isEmpty())
            {
                update oppsToBeUpdated;
            }
        }
         
           
     
    global void finish(Database.BatchableContext BC) 
    {
            // execute any post-processing operations
    }
}