objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Assigned_Sales_Rep__c.object
<CustomObject>
    <description>As a Dealer Sales Manager or above, I shall have the ability to reassign a customer account so that the newly reassigned sales rep can manage the account. This custom object stores the assigned sales rep information tied to a customer account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Sales Reps</relationshipLabel>
        <relationshipName>Assigned_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <defaultValue>$User.Dealer_Code__c</defaultValue>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Party_ID__c</fullName>
        <formula>Account__r.Party_ID__c</formula>
        <label>Party ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5)</booleanFilter>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>contains</operation>
                <value>Partner User</value>
            </filterItems>
            <filterItems>
                <field>$User.LastName</field>
                <operation>equals</operation>
                <valueField>User.LastName</valueField>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>PowerPartner</value>
            </filterItems>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>notContain</operation>
                <value>Partner User</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Sales Rep</label>
    <nameField>
        <displayFormat>ASR-{00000}</displayFormat>
        <label>ASR#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Sales Reps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Merge__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorAccountId__c</fullName>
        <label>SurvivorAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorPartyId__c</fullName>
        <label>SurvivorPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimAccountId__c</fullName>
        <label>VictimAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimPartyId__c</fullName>
        <label>VictimPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Merge</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>RowNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <externalId>true</externalId>
        <label>User Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_BatchMergeASR.cls
global class Vgtna_BatchMergeASR implements Database.Batchable<sObject>{
   global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = 'select id,Account__c,Sales_Rep__c,Sales_Rep__r.user_id__c,Party_Id__c,Dealer_Code__c,External_id__c from Assigned_Sales_Rep__c';
        system.debug('query-->'+query);
        return Database.getQueryLocator(query);
    } 
    global void execute(Database.BatchableContext BC, List<Assigned_Sales_Rep__c> asrList)
     {
         //Stores Surviver and Victim AccountIds from Merge table
         map<string,string> mapSurVic = new map<string,string>();
         //Stores Surviver and Victim PartyIds from Merge table
         map<string,string> mapSurVicPID = new map<string,string>();
         //List to update all ASR records with Surviving Account Ids
         list<Assigned_Sales_Rep__c> listUpdASR = new list<Assigned_Sales_Rep__c>();
         //List to delete all to-be duplicate victims as existing ASR with surviving details Exist
         list<Assigned_Sales_Rep__c> delList = new list<Assigned_Sales_Rep__c>();
         //list of Strings that can store all the Surviving PartyIds where we query using LIKE
         list<string> surPartyId = new list<string>();
          //Set that stores all the External Ids from ASR for surviving Records
         set<string> asrSurDet = new set<string>();
         string[] strSurPID = new String[]{};
             list<string> surPartyIdOnly = new list<string>();
             //Query on Merge table to collect details 
         for(merge__c m:[select id,name,SurvivorPartyId__c,VictimPartyId__c,Status__c,SurvivorAccountId__c,VictimAccountId__c
                                                        from Merge__c 
                                                       where Status__c = 'To Be Processed' and SurvivorAccountId__c <> null and VictimAccountId__c <> null])
         {
             mapSurVic.put(m.VictimAccountId__c, m.SurvivorAccountId__c);   
             mapSurVicPID.put(m.VictimPartyId__c, m.SurvivorPartyId__c);
             surPartyIdOnly.add(m.SurvivorPartyId__c);
             surPartyId.add('%'+m.SurvivorPartyId__c+'%');
             strSurPID.add('%'+m.SurvivorPartyId__c+'%');
         }
         //Collect External Ids of ASR for the surviving records
         //for(Assigned_Sales_Rep__c asr:[select id,Account__c,Sales_Rep__c,Sales_Rep__r.user_id__c,Party_Id__c,External_id__c from Assigned_Sales_Rep__c where External_Id__c like:surPartyId])
         for(Assigned_Sales_Rep__c asr:[select id,Account__c,Sales_Rep__c,Sales_Rep__r.user_id__c,Party_Id__c,External_id__c from Assigned_Sales_Rep__c where party_id__c IN :surPartyIdOnly])
         {
             asrSurDet.add(asr.External_id__c);
         }
         for(Assigned_Sales_Rep__c currASRRec: asrList)
         {
             if(mapSurVic.ContainsKey(currASRRec.Account__c))
             {
                 if(mapSurVicPID.containsKey(currASRRec.Party_ID__c))
                 {
                     string sSurExtId;
                     //Build the External Id of the surviving Record
                     if(String.isBlank(currASRRec.Dealer_Code__c)){
                 	 sSurExtId = mapSurVicPID.get(currASRRec.Party_ID__c)+'_'+currASRRec.Sales_Rep__r.user_id__c+'_';
                     }else
                     {
                       sSurExtId = mapSurVicPID.get(currASRRec.Party_ID__c)+'_'+currASRRec.Sales_Rep__r.user_id__c+'_'+currASRRec.Dealer_Code__c;  
                     }
                     //Check for Duplicate--Does ASR already Exist if we change the Victim ASR record
                     boolean result = asrSurDet.contains(sSurExtId);
                // integer isCount = [select count() from Assigned_Sales_Rep__c where external_id__c=:sSurExtId];
                // Delete Victim ASR if already exists
                     if(result){
                         delList.add(currASRRec);
                     }
                     //Update Victim ASR if it doesnt exist
                     else{
                         currASRRec.Account__c = mapSurVic.get(currASRRec.Account__c); 
                         listUpdASR.add(currASRRec);
                     }
                                 
                 }
             }             
            
         }
         if(delList.size()>0){
             Database.delete(delList,false);
         }
         if(listUpdASR.size()>0){
             Database.update(listUpdASR,false);
         }
     }
    global void finish(Database.BatchableContext BC) 
    {
        	database.executeBatch(new Vgtna_BatchMergeCustomerProfile(), 1000); 
            // execute any post-processing operations
    }

}