objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>Determines Brand based on Dealer Code</description>
        <formula>If(ISBLANK(Dealer_Code__c), &apos;&apos;, IF(ISNUMBER(LEFT(Dealer_Code__c, 1)),&apos;Volvo&apos;, &apos;Mack&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Party_ID_LastModifiedDate__c</fullName>
        <label>Party ID Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Account Record Type for Customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>Formula to derive Brand from Dealer Code on Account</description>
        <formula>If(ISBLANK(Account.Dealer_Code__c), &apos;&apos;, IF(ISNUMBER(LEFT(Account.Dealer_Code__c, 1)),&apos;Volvo&apos;, &apos;Mack&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Brand</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_Test_FetchCustomerActivities.cls
@isTest
private class Vgtna_Test_FetchCustomerActivities
{

    static testMethod void fetchTaskTestMethod1()
    {   
        User runAsUsr = [SELECT Id FROM User WHERE profile.Name='System Administrator' and isActive=true and UserRoleId!=null Limit 1];
        User testPartnerUser = new User();
        Account tstDealerAccount = new Vgtna_TestBuilder.AccountBuilder().setName('Test ACR PROCESS TRUCK CENTER').setRecordType(vgtna_Constants.ACCOUNT_CUSTOMER_RECORDTYPE).setPartyId().buildAndSave();
        tstDealerAccount.Party_ID_LastModifiedDate__c = System.today();
        update tstDealerAccount;
        system.debug('customer acc: '+[select id, recordtype.name from account where id =:tstDealerAccount.Id]);
        Account dealerAccount = new Vgtna_TestBuilder.AccountBuilder().setName('ADVANTAGE TRUCK CENTER').setRecordType(vgtna_Constants.ACCOUNT_DEALER_RECORDTYPE).setDealerCode('A112').buildAndSave();
        dealerAccount.IsPartner = true;
        //dealerAccount.ParentId = tstDealerAccount1.Id;
        update dealerAccount;
        Contact tstContact = new Vgtna_TestBuilder.ContactBuilder().setLastName(' Partner User').setFirstName('ACR Process').setEmail('testacrp@vive.com.invalid').setAccount(dealerAccount).buildAndSave();
       // AccountContactRelation acr = new AccountContactRelation(contactId = tstContact.Id, Roles = 'Sales Manager', AccountId=dealerAccount.Id);
        //insert acr;
        System.runAs(runAsUsr) {
            User tstUser = new Vgtna_TestBuilder.UserBuilder().setContact(tstContact).setlastName('Partner User').setEmail(tstContact.Email).setProfileId(vgtna_Constants.DEALER_USER_PROFILE).buildAndSave();
                
            tstUser.IsPortalEnabled=true;
            tstUser.UserRoleId=[Select Id from UserRole Where PortalAccountId=:dealerAccount.Id And PortalRole='Worker' Limit 1].Id;
            tstUser.Dealer_Brand__c = 'Mack';
            tstUser.Dealer_Code__c = 'A112';
            update tstUser;   
            testPartnerUser = tstUser;  
            AccountContactRelation acr = [SELECT Id, Roles FROM AccountContactRelation WHERE AccountId = :dealerAccount.Id AND ContactId = :tstContact.Id LIMIT 1];
            acr.Roles = 'Sales Manager';
            update acr;
        }        
        System.RunAs(testPartnerUser){
            Id custRec = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            system.debug('custRec: '+custRec);
            account a = new account();
            a.recordtypeId = custRec;
            a.Name = 'customer1';
            a.Party_id__c = '7439849393';
            insert a;
            //Account acc = [SELECT Id, recordtype.name FROM Account where recordtypeId = :custRec LIMIT 1];
            //system.debug('acc record: '+acc.recordtype.name);
            Task t = new Task();
            t.WhatId = a.Id;
            t.Account__c = a.Id;
            t.OwnerId = testPartnerUser.Id;
            t.Dealer_Code__c = 'A112';
            t.Subject = 'Call';
            t.ActivityDate = System.today();
            insert t;
            Event e = new Event();
            e.WhatId = a.Id;
            e.Subject = 'New Event';
            e.Account__c = a.Id;
            e.OwnerId = testPartnerUser.Id;
            e.Dealer_Code__c = 'A112';
            e.Subject = 'Call';
            e.DurationInMinutes= 1440;
            e.IsAllDayEvent = true;
            e.ActivityDate = System.today();
            insert e;
            Vgtna_FetchCustomerActivities.getCustActivities(a.Id,true,'activitiestab');
            Vgtna_FetchCustomerActivities.getLoggedUser();            
        }      
        
        //Naren: Add the View All condition to be False
        System.RunAs(testPartnerUser){
            //Account acc = [SELECT Id FROM Account LIMIT 1];
            Task t = new Task();
            //t.WhatId = tstDealerAccount.Id;
           // t.Account__c = tstDealerAccount.Id;
            t.OwnerId = testPartnerUser.Id;
            t.Dealer_Code__c = 'A112';
            t.Subject = 'Call';
            t.ActivityDate = System.today();
            insert t;
            Event e = new Event();
           // e.WhatId = tstDealerAccount.Id;
            e.Subject = 'New Event';
            //e.Account__c = tstDealerAccount.Id;
            e.OwnerId = testPartnerUser.Id;
            e.Dealer_Code__c = 'A112';
            e.Subject = 'Call';
            e.DurationInMinutes= 1440;
            e.IsAllDayEvent = true;
            e.ActivityDate = System.today();
            insert e;
            Vgtna_FetchCustomerActivities.getCustActivities('',False,'activitiestab');
            Vgtna_FetchCustomerActivities.getLoggedUser();
        }       
         
    }
    
    static testMethod void fetchTaskTestMethod2()
    {   
        User runAsUsr = [SELECT Id FROM User WHERE profile.Name='System Administrator' and isActive=true and UserRoleId!=null Limit 1];
        User testPartnerUser = new User();
        Account tstDealerAccount = new Vgtna_TestBuilder.AccountBuilder().setName('Test ACR PROCESS TRUCK CENTER').setRecordType(vgtna_Constants.ACCOUNT_CUSTOMER_RECORDTYPE).setPartyId().buildAndSave();
        tstDealerAccount.Party_ID_LastModifiedDate__c = System.today();
        update tstDealerAccount;
        Account dealerAccount = new Vgtna_TestBuilder.AccountBuilder().setName('ADVANTAGE TRUCK CENTER').setRecordType(vgtna_Constants.ACCOUNT_DEALER_RECORDTYPE).setDealerCode('A112').buildAndSave();
        dealerAccount.IsPartner = true;
        //dealerAccount.ParentId = tstDealerAccount1.Id;
        update dealerAccount;
        Contact tstContact = new Vgtna_TestBuilder.ContactBuilder().setLastName(' Partner User').setFirstName('ACR Process').setEmail('testacrp@vive.com.invalid').setAccount(dealerAccount).buildAndSave();
        System.runAs(runAsUsr) {
            User tstUser = new Vgtna_TestBuilder.UserBuilder().setContact(tstContact).setlastName('Partner User').setEmail(tstContact.Email).setProfileId(vgtna_Constants.DEALER_USER_PROFILE).buildAndSave();
                
            tstUser.IsPortalEnabled=true;
            tstUser.UserRoleId=[Select Id from UserRole Where PortalAccountId=:dealerAccount.Id And PortalRole='Worker' Limit 1].Id;
            tstUser.Dealer_Brand__c = 'Mack';
            tstUser.Dealer_Code__c = 'A112';
            update tstUser;   
            testPartnerUser = tstUser;  
        }        
        System.RunAs(testPartnerUser){
            //Account acc = [SELECT Id FROM Account LIMIT 1];
            Task t = new Task();
            //t.WhatId = tstDealerAccount.Id;
            //t.Account__c = tstDealerAccount.Id;
            t.OwnerId = testPartnerUser.Id;
            t.Dealer_Code__c = 'A112';
            t.Subject = 'Call';
            t.ActivityDate = System.today();
            insert t;
            Event e = new Event();
            //e.WhatId = tstDealerAccount.Id;
            e.Subject = 'New Event';
            //e.Account__c = tstDealerAccount.Id;
            e.OwnerId = testPartnerUser.Id;
            e.Dealer_Code__c = 'A112';
            e.Subject = 'Call';
            e.DurationInMinutes= 1440;
            e.IsAllDayEvent = true;
            e.ActivityDate = System.today();
            insert e;
            String recId;
            Vgtna_FetchCustomerActivities.getCustActivities('',false,'activitiestab');
        }    
            System.RunAs(testPartnerUser){
            //Account acc = [SELECT Id FROM Account LIMIT 1];
            Task t = new Task();
           // t.WhatId = tstDealerAccount.Id;
           // t.Account__c = tstDealerAccount.Id;
            t.OwnerId = testPartnerUser.Id;
            t.Dealer_Code__c = 'A112';
            t.Subject = 'Call';
            t.ActivityDate = System.today();
            insert t;
            Event e = new Event();
            //e.WhatId = tstDealerAccount.Id;
            e.Subject = 'New Event';
            //e.Account__c = tstDealerAccount.Id;
            e.OwnerId = testPartnerUser.Id;
            e.Dealer_Code__c = 'A112';
            e.Subject = 'Call';
            e.DurationInMinutes= 1440;
            e.IsAllDayEvent = true;
            e.ActivityDate = System.today();
            insert e;
            String recId;
            Vgtna_FetchCustomerActivities.getCustActivities(recId,true,'Activities Tab');
            Vgtna_FetchCustomerActivities.getLoggedUser();
        }       
    }
}