objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daycab_Volvo__c</fullName>
        <label>% Daycab</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Daycab__c</fullName>
        <label>% Daycab</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>Determines Brand based on Dealer Code</description>
        <formula>If(ISBLANK(Dealer_Code__c), &apos;&apos;, IF(ISNUMBER(LEFT(Dealer_Code__c, 1)),&apos;Volvo&apos;, &apos;Mack&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FE_Current_Volvo__c</fullName>
        <inlineHelpText>Current Fuel Efficiency</inlineHelpText>
        <label>FE Current</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FE_Goal_Volvo__c</fullName>
        <inlineHelpText>Target Fuel Efficiency</inlineHelpText>
        <label>FE Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FE_Goal__c</fullName>
        <inlineHelpText>Target Fuel Efficiency</inlineHelpText>
        <label>FE Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mack_National_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mack National Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mack_Sales_Target_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this account a target account for a dealer&apos;s sales plan?</inlineHelpText>
        <label>Mack Dealer Planned Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <inlineHelpText>Dealer code to receive credit for opportunity</inlineHelpText>
        <label>Assigned Dealer</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_ID_LastModifiedDate__c</fullName>
        <label>Party ID Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Make_Volvo__c</fullName>
        <label>Primary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Make__c</fullName>
        <label>Primary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Repair_Shop_Owned_Volvo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Repair Shop Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Repair_Shop_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Repair Shop Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Make_Volvo__c</fullName>
        <label>Secondary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Secondary_Make__c</fullName>
        <label>Secondary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sleeper_Volvo__c</fullName>
        <label>% Sleeper</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sleeper__c</fullName>
        <label>% Sleeper</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Strategic_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strategic Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trade_Cycle_Volvo__c</fullName>
        <label>Trade Cycle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trade_Cycle__c</fullName>
        <label>Trade Cycle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trades_Volvo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trades</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trades__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trades</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volvo_National_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Volvo National Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volvo_Sales_Target_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this account a target account for a dealer&apos;s sales plan?</inlineHelpText>
        <label>Volvo Sales Target Account</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Account Record Type for Customers</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Account Record Type for Dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>Customer_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Daycab__c</fullName>
        <label>% Daycab</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles (Dealer Account)</relationshipLabel>
        <relationshipName>Customer_Profiles1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>FE_Goal__c</fullName>
        <label>FE Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Make__c</fullName>
        <label>Primary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Repair_shop_owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Repair shop owned?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Make__c</fullName>
        <label>Secondary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sleeper__c</fullName>
        <label>% Sleeper</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Trade_Cycle__c</fullName>
        <label>Trade Cycle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trades__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trades</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Customer Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Mack</fullName>
        <active>true</active>
        <businessProcess>Volvo</businessProcess>
        <label>Mack</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volvo</fullName>
        <active>true</active>
        <businessProcess>Volvo</businessProcess>
        <label>Volvo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Merge__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorPartyId__c</fullName>
        <label>SurvivorPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimPartyId__c</fullName>
        <label>VictimPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Merge</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>RowNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Desired_Delivery_Date__c</fullName>
        <description>Desired date for Delivery of Vehicles</description>
        <label>Desired Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invite_Sales_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox used to provide visibility to the Opportunity to Internal Users as Defined by the Account Team Membership, sets up an Opportunity team based on OEM</description>
        <label>Invite Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Credited Dealer for Opportunity</inlineHelpText>
        <label>Assigned Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dealer Assigned Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Mack</fullName>
        <active>true</active>
        <businessProcess>Mack</businessProcess>
        <label>Mack</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volvo</fullName>
        <active>true</active>
        <businessProcess>Volvo</businessProcess>
        <label>Volvo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_Test_BatchMerge.cls
@isTest
public class Vgtna_Test_BatchMerge {
    public static testmethod void batchmerge(){
        User testPartnerUser = new User();
        
        User runAsUsr = [SELECT Id FROM User WHERE profile.Name='System Administrator' and isActive=true and UserRoleId!=null Limit 1];
        string dsm = 'District Sales Manager';
        string rfm = 'Regional Fleet Manager';
        string nam = 'National Accounts Manager';
        UserRole r,rP;
        User u,uP;
        
         System.runAs(runAsUsr){
             //Internal users
             rP = new UserRole(DeveloperName = 'RVP', Name = 'Regional Vice President');
        insert rP;
       	r = new UserRole(DeveloperName = 'DSM', Name = 'District Sales Manager',ParentRoleId =rP.id );
		insert r;
       uP = new User(
         //ProfileId = '00ef2000001Y2h3AAC',
          ProfileId = [select id from profile where name ='Mack Sales Rep'].id,
         LastName = 'lastname',
         Email = 'lastfirst@lastnamefirstname.com',
         Username = 'lastfirst@lastnamefirstname.com' + System.currentTimeMillis(),
         CompanyName = 'Volvo Trucks',
         Title = 'DSM',
         Alias = 'DSM',
          Dealer_Brand__c = 'Mack',
         TimeZoneSidKey = 'America/Los_Angeles',
         EmailEncodingKey = 'UTF-8',
         LanguageLocaleKey = 'en_US',
         LocaleSidKey = 'en_US',
         UserRoleId = rP.Id
		);
        insert uP;  
      u = new User(
         //ProfileId = '00ef2000001Y2h3AAC',
         ProfileId = [select id from profile where name ='Mack Sales Rep'].id,
         LastName = 'lastname',
         Email = 'lastfirst@lastnamefirstname.com',
         Username = 'lastfirst@lastnamefirstname.com' + System.currentTimeMillis(),
         CompanyName = 'Volvo Trucks',
         Title = 'DSM',
         Alias = 'DSM',
          Dealer_Brand__c = 'Mack',
         TimeZoneSidKey = 'America/Los_Angeles',
         EmailEncodingKey = 'UTF-8',
         LanguageLocaleKey = 'en_US',
         LocaleSidKey = 'en_US',
         UserRoleId = r.Id
		);
        insert u;
              //Accounts
              Account tstDealerAccount = new Vgtna_TestBuilder.AccountBuilder().setName('Test ACR PROCESS TRUCK CENTER').setRecordType(vgtna_Constants.ACCOUNT_CUSTOMER_RECORDTYPE).setPartyId().buildAndSave();
       		 tstDealerAccount.Party_ID_LastModifiedDate__c = System.today();
       		 update tstDealerAccount;
             
             Account tstCustAccount = new Vgtna_TestBuilder.AccountBuilder().setName('SurvivorAccount').setRecordType(vgtna_Constants.ACCOUNT_CUSTOMER_RECORDTYPE).setPartyIdConstant('S1234').setBillingCountryCode('US').setBillingPostalCode('561832323').buildAndSave();
             Account tstCustAccount1 = new Vgtna_TestBuilder.AccountBuilder().setName('VictimAccount').setRecordType(vgtna_Constants.ACCOUNT_CUSTOMER_RECORDTYPE).setPartyIdConstant('V1234').setBillingCountryCode('US').setBillingPostalCode('561832323').buildAndSave();
             tstCustAccount1.Strategic_Account__c = true;
             tstCustAccount1.Mack_National_Account__c = true;
             tstCustAccount1.Volvo_National_Account__c = true;
             tstCustAccount1.Trades__c = true;
             tstCustAccount1.Trade_Cycle_Volvo__c = 'testTrade';
             tstCustAccount1.Industry = 'Manufacturing';
             tstCustAccount1.Mack_Sales_Target_Account__c = true;
             tstCustAccount1.FE_Current_Volvo__c = 23;
             tstCustAccount1.Repair_Shop_Owned__c = true;
             tstCustAccount1.Repair_Shop_Owned_Volvo__c = true;
             tstCustAccount1.Volvo_Sales_Target_Account__c = true;
             tstCustAccount1.Mack_Sales_Target_Account__c = true;
             tstCustAccount1.Daycab__c = 23;
             tstCustAccount1.Daycab_Volvo__c = 32;
             tstCustAccount1.Sleeper__c = 24;
             tstCustAccount1.Sleeper_Volvo__c = 34;
             tstCustAccount1.FE_Goal__c = 12;
             tstCustAccount1.FE_Goal_Volvo__c = 89;
             tstCustAccount1.Trade_Cycle__c = 'TradeCycle';
             tstCustAccount1.Trade_Cycle_Volvo__c = 'Volvo';
             tstCustAccount1.Trades_Volvo__c = true;
             tstCustAccount1.Primary_Make__c = 'Freightliner';
             tstCustAccount1.Primary_Make_Volvo__c = 'Volvo';
             tstCustAccount1.Secondary_Make__c = 'Peterbilt';
             tstCustAccount1.Secondary_Make_Volvo__c = 'Mack';
             
             update tstCustAccount1;
             boolean b = false;
             tstCustAccount.Strategic_Account__c = b;
             tstCustAccount.Mack_National_Account__c = b;
             tstCustAccount.Volvo_National_Account__c = b;
             tstCustAccount.Trades__c = b;
             tstCustAccount.Trades_Volvo__c = b;
             tstCustAccount.Repair_Shop_Owned_Volvo__c = b;
             tstCustAccount.Trade_Cycle_Volvo__c = 'testTrade';
             tstCustAccount.Volvo_Sales_Target_Account__c = b;
             //tstCustAccount.Repair_Shop_Owned__c = b;
             //tstCustAccount.Mack_Sales_Target_Account__c = b;
             //tstCustAccount.Volvo_Sales_Target_Account__c = b;
             update tstCustAccount;
             //Account Team member
             AccountTeamMember newTeam = new AccountTeamMember(AccountId = tstCustAccount1.id,TeamMemberRole = 'District Sales Manager',UserId = u.Id);
        	insert newTeam;
             //Dealer Account
              Account tstDealerAccount1 = new Vgtna_TestBuilder.AccountBuilder().setName('CP Test Dealer Account').setRecordType(vgtna_Constants.ACCOUNT_DEALER_RECORDTYPE).setDealerCode('5887D').buildAndSave();
             tstDealerAccount.IsPartner = true;                
             update tstDealerAccount;
             //Contacts
             Contact tstContactP = new Vgtna_TestBuilder.ContactBuilder().setLastName(' Partner User').setFirstName('ACR Process').setEmail('testacrp@vive.com.invalid').setAccount(tstDealerAccount).buildAndSave();
             Contact tstContact = new Vgtna_TestBuilder.ContactBuilder().setAccount(tstCustAccount1).setEmail('tst@gm.com').setFirstName('FirstN').setLastName('LastN').buildAndSave();
             //User
             User tstUser = new Vgtna_TestBuilder.UserBuilder().setContact(tstContact).setlastName('Partner User').setEmail(tstContact.Email).setProfileId(vgtna_Constants.DEALER_USER_PROFILE).buildAndSave();   
            tstUser.IsPortalEnabled=true;
            tstUser.Dealer_Brand__c = 'Mack';
            tstUser.Dealer_Code__c = 'A112';
            update tstUser;   
            testPartnerUser = tstUser;	
             
             //Leads
             List<Lead> newPartnerLeads = new List<Lead>();
            
            Lead l1 = new Lead(LastName = 'Test1',IsConverted = true,ConvertedAccountId = tstCustAccount.Id, Company = 'Comp1',Email='test11@test.com.invalid',CountryCode = 'US',PostalCode = '07302', Brand__c = 'Volvo');
            newPartnerLeads.add(l1);
            
            Lead l3 = new Lead(LastName = 'Test3', Company = 'Comp3',
                                   Email='test13@test.com.invalid',Brand__c = 'Volvo',
                               		ConvertedAccountId = tstCustAccount1.Id,
                                   CountryCode = 'CA',PostalCode = 'L4N7GS',
                                   StateCode = 'ON',City='Toronto',IsConverted = true);
            newPartnerLeads.add(l3);
            
            insert newPartnerLeads;
   
  			//Activities
  			Task t = new Task();
            t.WhatId = tstCustAccount1.Id;
            t.Account__c = tstCustAccount1.Id;
            t.OwnerId = testPartnerUser.Id;
            t.Dealer_Code__c = 'A112';
            t.Subject = 'Call';
            t.ActivityDate = System.today();
            insert t;
            Event e = new Event();
            e.WhatId = tstCustAccount1.Id;
            e.Subject = 'New Event';
            e.Account__c = tstCustAccount1.Id;
            e.OwnerId = testPartnerUser.Id;
            e.Dealer_Code__c = 'A112';
            e.Subject = 'Call';
            e.DurationInMinutes= 1440;
            e.IsAllDayEvent = true;
            e.ActivityDate = System.today();
             insert e;
             //Opportunity
             Opportunity oppty = new Opportunity(
            AccountId=tstCustAccount1.Id,
            CloseDate=Date.Today().addDays(7),
            Desired_Delivery_Date__c=Date.Today().addDays(7),
            Brand__c = vgtna_Constants.VOLVO_BRAND,
            Name='TestTheOppty',
            OwnerId=testPartnerUser.Id,
            StageName='Identify',
            Partner_Account__c= tstDealerAccount.Id,
            Invite_Sales_Team__c=false);
              insert oppty;
             //Customer Profile.
            // Account acc = [Select id from Account where name= 'CustomerProfileTest' limit 1];
             Account accDealer = [Select id from Account where Dealer_Code__c = '5887D' limit 1];
             Customer_Profile__c CP = new Customer_Profile__c(Customer_Account__c = tstCustAccount1.id,
                                                             Dealer_Account__c = accDealer.Id);
             insert cp;
  			//Merge
             Merge__c m = new Merge__c();
             m.SurvivorPartyId__c = 'S1234';
             m.VictimPartyId__c = 'V1234';
             m.Status__c = 'To Be Processed';
             insert m;
             
         }
        System.runAs(runAsUsr){            
            Vgtna_PopulateMergeObj.getAccDetails(); 
            Vgtna_PopulateMergeObjONETIMELOAD.getAccDetailsOTL();
         }
    }
}