objects/Account.object
<CustomObject>
    <fields>
        <fullName>Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SurvivingPartyId__c</fullName>
        <label>SurvivingPartyId</label>
        <length>23</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/VGTNA_rerouteAccountController.cls
public with sharing class  VGTNA_rerouteAccountController{
 @AuraEnabled
    public static Account findAccount(Id accountid){        
     Account sur = [SELECT Party_Id__c,Id,description,SurvivingPartyId__c,name FROM Account WHERE id=:accountid];
      string survId = sur.SurvivingPartyId__c;
        if(survId !=null){
        	system.debug('surviving id'+sur);
        	return [SELECT Party_Id__c,Id,description,SurvivingPartyId__c,name FROM Account WHERE Party_Id__c=:survId];       
        }
        else{
            Account a = null;
             return a;
        }           
    }
}