objects/Account.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <description>Corporate Sales Rep FIeld</description>
        <label>Application</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Daycab__c</fullName>
        <label>% Daycab</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>Determines Brand based on Dealer Code</description>
        <formula>If(ISBLANK(Dealer_Code__c), &apos;&apos;, IF(ISNUMBER(LEFT(Dealer_Code__c, 1)),&apos;Volvo&apos;, &apos;Mack&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FE_Current__c</fullName>
        <inlineHelpText>Current Fuel Efficiency</inlineHelpText>
        <label>FE Current</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FE_Goal__c</fullName>
        <inlineHelpText>Target Fuel Efficiency</inlineHelpText>
        <label>FE Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Miles_Driven__c</fullName>
        <label>Miles Driven</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Make__c</fullName>
        <label>Primary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RSL_Cruise__c</fullName>
        <label>RSL Cruise</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSL_Pedal__c</fullName>
        <label>RSL Pedal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Target_Account__c</fullName>
        <formula>IF(TEXT($User.Dealer_Brand__c) = &apos;Mack&apos;, Mack_Sales_Target_Account__c, 
IF(TEXT($User.Dealer_Brand__c) = &apos;Volvo&apos;, Volvo_Sales_Target_Account__c, 
FALSE))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Is this account a target account for a dealer&apos;s sales plan?</inlineHelpText>
        <label>Sales Target Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Make__c</fullName>
        <label>Secondary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sleeper__c</fullName>
        <label>% Sleeper</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Trade_Cycle__c</fullName>
        <label>Trade Cycle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trades__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trades</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trailer_Types__c</fullName>
        <label>Trailer Types</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Warranty_Coverage__c</fullName>
        <label>Warranty Coverage</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Account Record Type for Customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>Customer_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Daycab__c</fullName>
        <label>% Daycab</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles (Dealer Account)</relationshipLabel>
        <relationshipName>Customer_Profiles1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>FE_Current__c</fullName>
        <label>FE Current</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FE_Goal__c</fullName>
        <label>FE Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Key_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Miles_Driven__c</fullName>
        <label>Miles Driven</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Make__c</fullName>
        <label>Primary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RSL_Cruise__c</fullName>
        <label>RSL Cruise</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSL_Pedal__c</fullName>
        <label>RSL Pedal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Target_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Target Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Make__c</fullName>
        <label>Secondary Make</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sleeper__c</fullName>
        <label>% Sleeper</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Trade_Cycle__c</fullName>
        <label>Trade Cycle</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trades__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trades</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trailer_Types__c</fullName>
        <label>Trailer Types</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Warranty_Coverage__c</fullName>
        <label>Warranty Coverage</label>
        <type>TextArea</type>
    </fields>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Customer Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dual_Branded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for dynamic branding in communities for the toggle experience.</description>
        <label>Dual Branded?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Dealer_Code__c</fullName>
        <formula>Contact.Account.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Dealer Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_CustomerProfileController.cls
public with sharing class Vgtna_CustomerProfileController {

    @AuraEnabled 
    public static user fetchUser(){
     // query current user information  
      User oUser = [select id,Name,Dealer_Brand__c,Dual_Branded__c,Dealer_Code__c,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                 FROM User Where id =: userInfo.getUserId()];
        return oUser;

    }
    
    @AuraEnabled 
    public static String getCustomerProfile(Id accountId, String dealerCode){
        Customer_Profile__c customerProfile = new Customer_Profile__c();
        
        try
        {
            customerProfile = [Select id 
                               from Customer_Profile__c
                               where Customer_Account__c = :accountId
                               and Dealer_Account__r.Dealer_Code__c =:dealerCode Limit 1];
            return customerProfile.Id;
        }
        catch(Exception e)
        {
            // check if logged in user can create a customer profile
            	if (Schema.sObjectType.Customer_Profile__c.fields.Customer_Account__c.isCreateable())
                {
                   Account dealerAccount = new Account();
                   try
                   {
                       dealerAccount =[Select id
                                       from Account
                                       where Dealer_Code__c =:dealerCode limit 1];
                       return dealerAccount.Id;
                   }
                    catch(Exception ex)
                    {
                        return 'Insufficient privilege';
                    }
                }
                else
                {
                    return 'Insufficient privilege';
                }
            
        }
        
        
    }
  /**  
    @AuraEnabled 
    public static String getUserType(){
    //  Id i = Id.valueOf(accountIdString);
        String userType = [select UserType  
              FROM User Where Id =: UserInfo.getUserId() limit 1].UserType;
        System.debug('in GetCustomerProfileId, with userType:' + userType);
      return userType;
    }
    
    **/
/**
	@AuraEnabled
   // public static List<Customer_Profile__c> getCustomerProfileId(Id recordId) {
    public static Map<String, Id> getCustomerProfileId(Id accountId) {
        System.debug('in GetCustomerProfileId, with accntid:' + accountId);
  //[Select My_Position__c From User Where Id = :UserInfo.getUserId()][0].My_Position__c;
        Map<String, Id> results = new Map<String,Id>();
       
        Id customerProfileId;
        String sDealerCode = [select Primary_Dealer_Code__c  
              FROM User Where id =: UserInfo.getUserId() limit 1].Primary_Dealer_Code__c; //Dealer_Code__c;
        System.debug('in GetCustomerProfileId, with dealerCode:' + sDealerCode);
        String userType = Vgtna_CustomerProfileController.getUserType();
        if ( userType == 'PowerPartner')
            customerProfileId = [SELECT Customer_Account__c,Id FROM Customer_Profile__c 
                                WHERE Customer_Account__c = :accountId  AND Dealer_Account__r.Dealer_Code__c  = :sDealerCode LIMIT 1].Id; 
        else
            customerProfileId = [SELECT Customer_Account__c,Id FROM Customer_Profile__c 
                                WHERE Customer_Account__c = :accountId   LIMIT 1].Id; 
   **/         
        //            FROM User Where id =: UserInfo.getUserId() limit 1].Dealer_Code__c;
        /*  String sDealerCode = [Select Dealer_Code__c
                              From User
                              Where Id = :userInfo.getUserId() Limit 1];
        */
       // System.debug('in custom prof controller, cust Prof Id = '+ customerProfileId);
        //String recordIdstr = '0013B00000V5NK7QAN';
        //Id i = Id.valueOf(recordIdstr);

/*
        sDealerCode = '2701K';
        // List<Customer_Profile__c> lCustomerProfile 
        List<Customer_Profile__c> lCustomerProfile = [Select Application__c, Customer_Account__c, Daycab__c, Dealer_Account__c, FE_Current__c, FE_Goal__c, Id, 
               Key_Account__c, Miles_Driven__c, Name, OwnerId, Primary_Make__c, RSL_Cruise__c, RSL_Pedal__c, Sales_Target_Account__c, 
               Secondary_Make__c, Sleeper__c, Trade_Cycle__c, Trades__c, Trailer_Types__c, Warranty_Coverage__c 
               From Customer_Profile__c ];
        */      
                                                     
        /*
         *  Where Customer_Account__c = :i
               And Dealer_Account__r.Dealer_Code__c = :sDealerCode
*/
    //    System.debug('in custom prof controller, customer Profiles  = ' + lCustomerProfile);
        
       // return lCustomerProfile;
 /**     results.put(userType, customerProfileId);
        System.debug('my map result' + results);
        return results ;
    }
**/
}