objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Account Record Type for Customers</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Account Record Type for Dealers</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Profile__c.object
<CustomObject>
    <description>As of 7/31/2019 this should only be available for Mack Intenal Users and as a relatedl list under Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profiles</relationshipLabel>
        <relationshipName>Account_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles</relationshipLabel>
        <relationshipName>Customer_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Account__c</fullName>
        <label>Dealer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Profiles (Dealer Account)</relationshipLabel>
        <relationshipName>Customer_Profiles1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Customer Profile</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Customer Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_CustomerProfileControllerTest.cls
@isTest
public class Vgtna_CustomerProfileControllerTest 
{

    static testMethod void testCustomerProfile() 
    {
        Vgtna_CustomerProfileController.fetchUser();
        Vgtna_CustomerProfileController.getCustomerProfile('001000000ABYUIO','D5009');
        
        User runAsUsr = [SELECT Id FROM User WHERE profile.Name='System Administrator' and isActive=true and UserRoleId!=null Limit 1];
         System.RunAs(runAsUsr)
         {
             // Create customer account
             Account tstCustAccount = new Vgtna_TestBuilder.AccountBuilder().setName('CustomerProfileTest').setRecordType(vgtna_Constants.ACCOUNT_CUSTOMER_RECORDTYPE).setPartyId().buildAndSave();
             
             // Create the Dealer Account
                Account tstDealerAccount = new Vgtna_TestBuilder.AccountBuilder().setName('CP Test Dealer Account').setRecordType(vgtna_Constants.ACCOUNT_DEALER_RECORDTYPE).setDealerCode('5887D').buildAndSave();
                tstDealerAccount.IsPartner = true;                
                update tstDealerAccount;
             
             // Create the Contact that will be converted into the Partner User
                Contact tstContact = new Vgtna_TestBuilder.ContactBuilder().setLastName('Partner User').setFirstName('CP Test').setEmail('testCP@aol.com').setAccount(tstDealerAccount).buildAndSave();
                system.debug('*** contact '+tstContact);
             
             // Create the Partner User
             	User testPartnerUser = new User();
             	User tstUser = new Vgtna_TestBuilder.UserBuilder().setContact(tstContact).setlastName('CP Partner User').setEmail(tstContact.Email).setProfileId(vgtna_Constants.DEALER_USER_PROFILE).buildAndSave();
            
                 tstUser.IsPortalEnabled=true;
                 tstUser.UserRoleId=[Select Id 
                                     From UserRole 
                                     Where PortalAccountId=:tstDealerAccount.Id 
                                     And PortalRole='Manager' Limit 1].Id;
                 update tstUser;
                 testPartnerUser = tstUser;

         }
        
        System.RunAs(runAsUsr)
        {
            Account acc = [Select id from Account where name= 'CustomerProfileTest' limit 1];
            Account accDealer = [Select id from Account where Dealer_Code__c = '5887D' limit 1];
            
            Vgtna_CustomerProfileController.getCustomerProfile(acc.id,'5887D');
            
            Customer_Profile__c CP = new Customer_Profile__c(Customer_Account__c = acc.id,
                                                             Dealer_Account__c = accDealer.Id);
            
            insert CP;
            Vgtna_CustomerProfileController.getCustomerProfile(acc.id,'5887D');
            
            Account_Profile__c AP = new Account_Profile__c(Account__c = acc.Id);
			insert AP;
            
        }
    }
    
}