objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>Determines Brand based on Dealer Code</description>
        <formula>If(ISBLANK(Dealer_Code__c), &apos;&apos;, IF(ISNUMBER(LEFT(Dealer_Code__c, 1)),&apos;Volvo&apos;, &apos;Mack&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SurvivingAccountId__c</fullName>
        <label>SurvivingAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Customer_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the WhatId from the Activity when the WhatId is an Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Activities</relationshipLabel>
        <relationshipName>CustomerActivities_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedBy_Profile__c</fullName>
        <label>CreatedBy Profile</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <label>Dealer Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Volvo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field tells if the activities are created by Dealer User(Partner User) or not</description>
        <label>IsPartner</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Activity</label>
    <nameField>
        <label>Customer Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Dealer_Code__c</fullName>
        <formula>Contact.Account.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Dealer Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_TaskTriggerHelper.cls
public with sharing class Vgtna_TaskTriggerHelper {
    public static void populateDealerCode(List<Task> newList) {
        User usr = [SELECT Id, Dealer_Code__c,Dealer_Brand__C, ContactId, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()];
        for(Task T : newList) {
            T.Dealer_Code__c = String.isNotBlank(usr.Dealer_Code__c)?usr.Dealer_Code__c:'';
             T.Brand__C = String.isNotBlank(usr.Dealer_Brand__C)?usr.Dealer_Brand__C:'';
            T.CreatedBy_Profile__c = usr.Profile.Name;
            if(usr.ContactId != null) {
                t.IsVisibleInSelfService = true;
            }
        }
    }
//Rajesh Adding Below method
    public static void populateSurvivorAccount(List<Task> newList)
    {
        map<id,id> taskAccMap = new map<id,id>();
        for(Task t: newList){
            if(T.WhatId != null && String.ValueOf(T.WhatId).StartsWith('001')&&trigger.isInsert){
                taskAccMap.put(t.Id,t.WhatId);
            }
            else if(T.Account__c != null && String.ValueOf(T.Account__c).StartsWith('001')&&trigger.isUpdate){
                taskAccMap.put(t.Id,t.Account__c);
            }
        }
        map<id,id> surVic = new Map<id,id>();
        for(Account a:[select SurvivingAccountId__c,id from Account where id = :taskAccMap.values()]){
            if(a.SurvivingAccountId__c !=null){
                surVic.put(a.id,a.SurvivingAccountId__c);
            }
        }
        for(Task t:newList){
            if(T.WhatId != null && String.ValueOf(T.WhatId).StartsWith('001') && trigger.isInsert){
                if(surVic.get(T.WhatId)!=null){
                    t.WhatId = surVic.get(T.WhatId);
                }
            }
            else if(T.Account__c != null && String.ValueOf(T.Account__c).StartsWith('001') && trigger.isUpdate){
                if(surVic.get(T.Account__c)!=null)    {
                    t.Account__c = surVic.get(T.Account__c);
                }
            }
        }
    }//End populateSurvivorAccount    
    
    public static void updateActivityType(List<Task> newList) {
        List<Id> tIds = new List<Id>();
        for(Task t : newlist) {
            tIds.add(t.Id);
        }    
        if(tIds.size() > 0) {
            futureUpdateActType(tIds);
        }
    }
    
    @future
    public static void futureUpdateActType(List<Id> tIds) {
        List<Task> tlist = [SELECT Id, TaskSubtype, Activity_Type__c FROM Task WHERE Id IN :tIds];
        for(Task t : tlist) {
            t.Activity_Type__c = t.TaskSubtype;
        }
        update tlist;
    }
    
    public static void reparentAccTask(List<Task> newList, Map<Id, Task> oldMap, Boolean isInsert) {
    system.debug('newlist: '+newlist[0]+'--ownerid--'+newList[0].OwnerId);
        Id loggedUserId = UserInfo.getUserId();
        List<Task> newTask = new List<Task>();
        try {
            for(Task T : newList) {
                if(T.WhatId != null && String.ValueOf(T.WhatId).StartsWith('001') && isInsert) {
                    newTask.add(T);
                } else if(T.WhatId != null && String.ValueOf(T.WhatId).StartsWith('001') && !isInsert && (T.OwnerId != oldMap.get(T.Id).OwnerId || T.WhatId != oldMap.get(T.Id).WhatId)) { 
                    newTask.add(T);
                }
            }
            if(!newTask.isEmpty()) {
                //The variable tIdOwnAccIdMap stores the taskId in the key and 
                //the combination of CustomerActivity Id 
                Map<Id, String> tIdOwnAccIdMap = new Map<Id, String>();
                List<Id> tOwnerId = new List<Id>();
                List<Id> tIdsToInsertCustAct = new List<Id>();
                Map<Id, Customer_Activity__c> caMap = new Map<Id, Customer_Activity__c>();
                
                for(Task t : newTask) {
                system.debug('t.id: '+t.Id);
                    townerId.add(t.OwnerId);
                }
                for(Customer_Activity__c ca : [SELECT Id, OwnerId FROM Customer_Activity__c WHERE OwnerId IN :townerId]) {
                    caMap.put(ca.OwnerId, ca);
                }
                for(Task t  : newTask) {
                    if(caMap.containsKey(t.OwnerId)) {
                        tIdOwnAccIdMap.put(t.Id, caMap.get(t.OwnerId).Id);
                    } else {
                        tIdsToInsertCustAct.add(t.Id);
                    }
                }
                system.debug('tIdOwnIdMap0: '+tIdOwnAccIdMap);
                if(!tIdOwnAccIdMap.isEmpty() || !tIdsToInsertCustAct.isEmpty()) {
                    updateAccTasksOwnerId(tIdOwnAccIdMap, tIdsToInsertCustAct, loggedUserId);
                }
            }
        } catch (exception e) {
            System.debug('exception occured in the method Vgtna_TaskTriggerHelper.reparentAccTaskat line: '+e.getLineNumber()+' with exception '+e.getMessage());
        }
    }
    
    @future
    public static void updateAccTasksOwnerId(Map<Id, String> tIdOwnAccIdMap, List<Id> tIdsToInsertCustAct, Id loggedUserId) {
        try {
            Map<Id, Task> tMap = new Map<Id, Task>([SELECT Id, OwnerId, WhatId, WhoId, Status FROM Task WHERE Id IN :tIdsToInsertCustAct OR Id IN :tIdOwnAccIdMap.keySet()]);
            User usr = [SELECT Id, Dealer_Brand__c, ContactId, Dealer_Code__c,Primary_Dealer_code__c, Profile.Name FROM User WHERE Id = :loggedUserId];
            List<Task> updateTasks = new List<Task>();
            List<Customer_Activity__c> caList = new List<Customer_Activity__c>();
            Map<Id, List<Id>> ownIdTaskIdsMap = new Map<Id, List<Id>>();
            Map<Id, Customer_Activity__c> caOwnIdCaMap = new Map<Id, Customer_Activity__c>();
            system.debug('tIdOwnIdMap: '+tIdOwnAccIdMap);
            if(!tIdOwnAccIdMap.isEmpty()) {
                for(Id tId : tIdOwnAccIdMap.keySet()) {
                    Task t = new Task();
                    t.Id = tId;
                    t.Account__c = tMap.get(tId).WhatId;
                    //t.Status = tMap.get(tId).Status;
                    t.WhoId = null;
                    t.WhatId = tIdOwnAccIdMap.get(tId);
                    t.Brand__c = usr.Dealer_Brand__c;
                    t.Dealer_code__c = usr.Dealer_code__c;
                    updateTasks.add(t);
                }
            }
            if(!tIdsToInsertCustAct.isEmpty()) {
                for(Id tId : tIdsToInsertCustAct) {
                    if(!ownIdTaskIdsMap.containsKey(tMap.get(tId).OwnerId)) {
                        ownIdTaskIdsMap.put(tMap.get(tId).OwnerId, new List<Id>{tId});
                    } else {
                        ownIdTaskIdsMap.get(tMap.get(tId).OwnerId).add(tId);
                    }
                    Customer_Activity__c ca = new Customer_Activity__c();
                    ca.Name = userInfo.getFirstname()+' '+userInfo.getLastName();
                    ca.OwnerId = tMap.get(tId).OwnerId;
                    ca.Dealer_Brand__c = usr.Dealer_Brand__c;
                    ca.CreatedBy_Profile__c = usr.Profile.Name;
                    if(usr.contactId != null) {
                        ca.IsPartner__c = true;
                    }
                    caList.add(ca);
                }
                if(!caList.isEmpty()) {
                    insert caList;
                    for(Customer_Activity__c ca : caList) {
                        caOwnIdCaMap.put(ca.OwnerId, ca);
                    }
                    for(Id tOwnId : ownIdTaskIdsMap.keySet()) {
                        for(Id tId : ownIdTaskIdsMap.get(tOwnId)) {
                            Task t = new Task();
                            t.Id = tId;
                            t.Account__c = tMap.get(tId).WhatId;
                            //t.Status = tMap.get(tId).Status;
                            t.Brand__c = usr.Dealer_Brand__c;
                            t.WhatId = caOwnIdCaMap.get(tOwnId).Id;
                            t.WhoId = null;
                            t.Dealer_code__c = usr.Dealer_code__c;
                            updateTasks.add(t);
                        }
                    }
                    
                }
            }
            if(!updateTasks.isEmpty()) {
                update updateTasks;
                
            }
        } catch (exception e) {
            System.debug('exception occured in the method Vgtna_TaskTriggerHelper.updateAccTasksOwnerId at line: '+e.getLineNumber()+' with exception '+e.getMessage());
        }
    }
}