objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>Determines Brand based on Dealer Code</description>
        <formula>If(ISBLANK(Dealer_Code__c), &apos;&apos;, IF(ISNUMBER(LEFT(Dealer_Code__c, 1)),&apos;Volvo&apos;, &apos;Mack&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Party_ID__c</fullName>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Assigned_Sales_Rep__c.object
<CustomObject>
    <description>As a Dealer Sales Manager or above, I shall have the ability to reassign a customer account so that the newly reassigned sales rep can manage the account. This custom object stores the assigned sales rep information tied to a customer account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Sales Reps</relationshipLabel>
        <relationshipName>Assigned_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <defaultValue>$User.Dealer_Code__c</defaultValue>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_ID__c</fullName>
        <formula>Account__r.Party_ID__c</formula>
        <label>Party ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address__c</fullName>
        <formula>Account__r.BillingStreet &amp; &quot;, &quot; &amp;
Account__r.BillingCity &amp; &quot;, &quot; &amp;
Account__r.BillingState &amp; &quot; &quot; &amp;
Account__r.BillingPostalCode &amp; &quot; &quot; &amp;
Account__r.BillingCountry</formula>
        <label>Primary Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5)</booleanFilter>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>contains</operation>
                <value>Partner User</value>
            </filterItems>
            <filterItems>
                <field>$User.LastName</field>
                <operation>equals</operation>
                <valueField>User.LastName</valueField>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>PowerPartner</value>
            </filterItems>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>notContain</operation>
                <value>Partner User</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Sales_Reps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Sales Rep</label>
    <nameField>
        <displayFormat>ASR-{00000}</displayFormat>
        <label>ASR#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Sales Reps</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Dealer_Code__c</fullName>
        <formula>Contact.Account.Dealer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Dealer Code</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_FetchAssignedSalesRep.cls
public with sharing class Vgtna_FetchAssignedSalesRep {
    @AuraEnabled 
    public static List<wrapASR> getAssignedSalesRep(String recId) {
        try {
            Id loggedUserId = userInfo.getUserId();
            Map<Id, User> uMap = new Map<Id, User>([SELECT Id, Dealer_Code__c, Dealer_Brand__c, ContactId, Primary_Dealer_Code__c, Profile.Name FROM User WHERE Id = :UserInfo.getUserId()]);
            List<Assigned_Sales_Rep__c> asrList = [SELECT Id, Name, Account__c, Account__r.Name, Dealer_Code__c, Sales_Rep__c, Party_ID__c, Primary_Address__c, OwnerId, Owner.Name FROM Assigned_Sales_Rep__c WHERE Account__c = :recId AND Dealer_Code__c = :uMap.get(loggedUserId).Dealer_Code__c];
            List<wrapASR> wrapASRList = new List<wrapASR>();
            for(Assigned_Sales_Rep__c asr : asrList) {
                wrapASR asrRec = new wrapASR();
                asrRec.ASRName = asr.Name;
                asrRec.ASRLink = '/'+asr.Id;
                asrRec.PartyId = asr.Party_ID__c;
                asrRec.Address = asr.Primary_Address__c;
                asrRec.SalesRepLink = '/'+asr.OwnerId;
                asrRec.SalesRepName = asr.Owner.Name;
                asrRec.accountName = asr.Account__r.Name;
                wrapASRList.add(asrRec);
            }
            return wrapASRList;
        } catch (exception e) {
            System.debug('exception occured at line number: '+e.getLineNumber()+' with error '+e.getMessage());
            return null;
        }
    }
    
    @AuraEnabled 
    public static String deleteASR(String recId) {
        try {    
            if(String.isNotBlank(recId)) {
                List<Assigned_Sales_Rep__c> asr = [SELECT Id FROM Assigned_Sales_Rep__c WHERE Id = :recId];
                if(!asr.isEmpty()) {
                    delete asr;
                    return 'Success';
                }
            }
            return 'Record not found';
        } catch(exception e) {
            return 'Error: Exception '+e.getMessage()+' occured at line number '+e.getLineNumber();
        }
    }
    
    public class wrapASR {
        @AuraEnabled public String ASRName;
        @AuraEnabled public String ASRLink;
        @AuraEnabled public String PartyId;
        @AuraEnabled public String Address;
        @AuraEnabled public String Street;
        @AuraEnabled public String State;
        @AuraEnabled public String City;
        @AuraEnabled public String PostalCode;
        @AuraEnabled public String Country;
        @AuraEnabled public String SalesRepLink;
        @AuraEnabled public String SalesRepName;
        @AuraEnabled public String accountName;
        
        public wrapASR(){
            ASRName = '';
            ASRLink = '';
            PartyId = '';
            Address = '';
            Street = '';
            State = '';
            City = '';
            PostalCode = '';
            Country = '';
            SalesRepLink = '';
            SalesRepName = '';
            accountName = '';
            
        }
    }
}