objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Merge__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorAccountId__c</fullName>
        <label>SurvivorAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorPartyId__c</fullName>
        <label>SurvivorPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimAccountId__c</fullName>
        <label>VictimAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimPartyId__c</fullName>
        <label>VictimPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Merge</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>RowNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Vgtna_BatchMergeContacts.cls
global class Vgtna_BatchMergeContacts implements Database.Batchable<sObject>{
     global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = 'select id,name,AccountId from Contact';
        //String query = 'select id,name,AccountId,Account.Name from Contact where AccountId in(select VictimAccountId__c from merge__c)';
        system.debug('query-->'+query);
        return Database.getQueryLocator(query);
    }

     global void execute(Database.BatchableContext BC, List<Contact> conList)
     {
         map<string,string> mapSurVic = new map<string,string>();
        list<Contact> lstUpdContacts = new list<Contact>();
         for(merge__c m:[select id,name,SurvivorPartyId__c,VictimPartyId__c,Status__c,SurvivorAccountId__c,VictimAccountId__c
                                                        from Merge__c 
                                                       where Status__c = 'To Be Processed' and SurvivorAccountId__c <> null and VictimAccountId__c <> null])
         {
             mapSurVic.put(m.VictimAccountId__c, m.SurvivorAccountId__c);             
         }
        system.debug('==mapSurVic=='+mapSurVic);
        for(Contact c:conList)
        {
            if(mapSurVic.containsKey(c.AccountId)){
                c.AccountId = mapSurVic.get(c.AccountId);
            }
            lstUpdContacts.add(c);
        }
         System.debug('lstUpdContacts=='+lstUpdContacts);
         if(lstUpdContacts.size()>0){
       	 database.update(lstUpdContacts,false);
    	}
     }
    
    global void finish(Database.BatchableContext BC) 
    {
        	database.executeBatch(new Vgtna_BatchMergeASR(), 500); 
            // execute any post-processing operations
    }
}