objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <label>Dealer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Mack</fullName>
        <active>true</active>
        <businessProcess>Volvo</businessProcess>
        <label>Mack</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <businessProcess>Mack</businessProcess>
        <label>Other</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volvo</fullName>
        <active>true</active>
        <businessProcess>Volvo</businessProcess>
        <label>Volvo</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dual_Branded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for dynamic branding in communities for the toggle experience.</description>
        <label>Dual Branded?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vgtna_LeadRecordTypeSelectorController.cls
public class Vgtna_LeadRecordTypeSelectorController 
{

    @AuraEnabled 
    public static user fetchUser(){
     // query current user information  
      User oUser = [select id,Name,Dealer_Brand__c,Dual_Branded__c,Dealer_Code__c,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                 FROM User Where id =: userInfo.getUserId()];
        return oUser;

    }
    
    @AuraEnabled
    public static List<RecordType> getListOfRecordType(){
        
        User oUser = [select id,Name,Dealer_Brand__c,Dual_Branded__c,Dealer_Code__c,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                 FROM User Where id =: userInfo.getUserId() limit 1];
        Boolean isCommunityUser = oUser.IsPortalEnabled;
        String dealerBrand = oUser.Dealer_Brand__c;
        
        List<SelectOption> recordTypes = new List<SelectOption>();
        List<RecordType> rtNames = new List<RecordType>(); 
        RecordTypeInfo inf;
         RecordType otherRT;
        // Save off Other record ID to be used later.
            for(RecordTypeInfo info: Lead.SObjectType.getDescribe().getRecordTypeInfos()) {
                if(  info.getName() == System.Label.Vgtna_Other_OEM) {
                    //otherRT = info.getRecordTypeId();
                    inf  = info;
                    otherRT = new RecordType(Id = info.getRecordTypeId(),Name = info.getName());
                }               
            }
        if(isCommunityUser == true && (dealerBrand != null || dealerBrand != ''))
        {
             for(RecordTypeInfo info: Lead.SObjectType.getDescribe().getRecordTypeInfos()) {
                    if(info.isAvailable() && info.getName()== dealerBrand) {
                        recordTypes.add(new SelectOption(info.getRecordTypeId(), info.getName()));
                        rtNames.add(new RecordType(Id = info.getRecordTypeId(),Name = info.getName()));
                       
                    }
        		}
             rtNames.add(otherRT);
            
            /**if(dealerBrand == 'Volvo')
             {
                 for(RecordTypeInfo info: Lead.SObjectType.getDescribe().getRecordTypeInfos()) {
                    if(info.isAvailable() && info.getName()!= System.Label.Vgtna_Master_RT && info.getName()!='Mack') {
                        recordTypes.add(new SelectOption(info.getRecordTypeId(), info.getName()));
                        rtNames.add(new RecordType(Id = info.getRecordTypeId(),Name = info.getName()));
                    }
        		}
             }
            if(dealerBrand == 'Mack')
             {
                 for(RecordTypeInfo info: Lead.SObjectType.getDescribe().getRecordTypeInfos()) {
                    if(info.isAvailable() && info.getName()!= System.Label.Vgtna_Master_RT && info.getName()!='Volvo') {
                        recordTypes.add(new SelectOption(info.getRecordTypeId(), info.getName()));
                        rtNames.add(new RecordType(Id = info.getRecordTypeId(),Name = info.getName()));
                    }
        		}
             }**/
            
            
            
        }
        else
        {
            for(RecordTypeInfo info: Lead.SObjectType.getDescribe().getRecordTypeInfos()) {
                if(info.isAvailable() && info.getName()!= System.Label.Vgtna_Master_RT ) {
                    recordTypes.add(new SelectOption(info.getRecordTypeId(), info.getName()));
                    rtNames.add(new RecordType(Id = info.getRecordTypeId(),Name = info.getName()));
                   
            	}
        	}
            // rtNames.add(otherRT);
        }
            

        // Include these next 3 lines to output the results during development and debugging
        for( SelectOption selopt: recordTypes ) {
            System.debug( selopt.getLabel() + ',' + selopt.getValue() );
        }
        return rtNames;   
       
    }
    
}