objects/Lead.object
<CustomObject>
    <fields>
        <fullName>SurvivingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SurvivingAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Merge__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorAccountId__c</fullName>
        <label>SurvivorAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurvivorPartyId__c</fullName>
        <label>SurvivorPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimAccountId__c</fullName>
        <label>VictimAccountId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VictimPartyId__c</fullName>
        <label>VictimPartyId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Merge</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>RowNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Vgtna_BatchMergeLeads.cls
global class Vgtna_BatchMergeLeads implements Database.Batchable<sObject>{
     global Database.QueryLocator start(Database.BatchableContext BC) 
     {
        String query = 'select id,ConvertedAccountId from Lead where ConvertedAccountId<>null';
        system.debug('query-->'+query);
        return Database.getQueryLocator(query);
     }
    global void execute(Database.BatchableContext BC, List<Lead> leadList)
     {
         map<string,string> mapSurVic = new map<string,string>();
        list<Lead> lstUpdLeads = new list<Lead>();
         for(merge__c m:[select id,name,SurvivorPartyId__c,VictimPartyId__c,Status__c,SurvivorAccountId__c,VictimAccountId__c
                                                        from Merge__c 
                                                       where Status__c = 'To Be Processed' and SurvivorAccountId__c <> null and VictimAccountId__c <> null])
         {
             mapSurVic.put(m.VictimAccountId__c, m.SurvivorAccountId__c);             
         }
         for(Lead currLeadRec:leadList)
        {
            if(mapSurVic.containsKey(currLeadRec.ConvertedAccountId)){
                currLeadRec.SurvivingAccount__c = mapSurVic.get(currLeadRec.ConvertedAccountId);
            }
            lstUpdLeads.add(currLeadRec);
        }
         System.debug('lstUpdLeads=='+lstUpdLeads);
         if(lstUpdLeads.size()>0){
       	 database.update(lstUpdLeads,false);
    	}
     }
    global void finish(Database.BatchableContext BC) 
    {
        //Vgtna_MergeAccountDetails.mergeAccDet();
        database.executeBatch(new Vgtna_BatchMergeAccountTeam(), 1000);  
            // execute any post-processing operations
    }
}