objects/User.object
<CustomObject>
    <fields>
        <fullName>Dealer_Brand__c</fullName>
        <description>To capture OEM</description>
        <label>Dealer Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Volvo</fullName>
                    <default>true</default>
                    <label>Volvo</label>
                </value>
                <value>
                    <fullName>Mack</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                    <isActive>false</isActive>
                    <label>Both</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <description>This field is used in the lightning component to stamp the dealer code a user is currently on to kick-start other actions.</description>
        <label>Dealer Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SalesforceIntegrationController.cls
public class SalesforceIntegrationController {
    
	@AuraEnabled
    public static List<SObject> getUserProfile() {
      return [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1];
  	}
    
    @AuraEnabled
    public static Map<String, List<SObject>> getUserInformation() {
        //get user information.
        Map<String, List<SObject>> userinformationMap = new Map<String, List<SObject>>();
        List<SObject> profileinfo = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1];
        userinformationMap.put('profile',profileinfo);
     	List<SObject> userinfo = [SELECT CreatedDate,UserRole.Name,Name,Dealer_Brand__c, LastLoginDate,LocaleSidKey,Manager.Name,TimeZoneSidKey,Department,Id,Division, Dealer_Code__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        userinformationMap.put('user',userinfo);
        return userinformationMap;  
    }
}